BOT_DETRIGGER = "!stop"
BOT_USERNAME = "DefenderBot"
BOT_DISCLAIMER = "*This reply was generated automatically using AI.*"
BOT_TRIGGER_REPLY = "Defense activated for 3 days. Tell me !stop to deactivate defense early."
BOT_DETRIGGER_REPLY = "Defense deactivated."
BLACKLIST = ["[deleted]", "AutoModerator", "DefenderBot"]
SUB_BLACKLIST = ["AskReddit"]
SLEEP_TIME = 60
AI_MODEL = "gpt-3.5-turbo"
AI_MAX_TOKENS = 512 # Max for response
MAX_WATCHLIST_AGE = 3 # Age to autodelete watchlists in days
